### ISSUE TITLE
Arguments to CMakeScripts/ScriptCMakeBuild

### ISSUE THREAD

**Issue by rondiplomatico** [OpenCMISS/manage#1]
Why is there the extra definition -DCMAKE_MINIMUM_REQUIRED_VERSION=2.6?
It's not used anywhere in the script and the [CMake docs](http://www.cmake.org/cmake/help/v3.2/variable/CMAKE_MINIMUM_REQUIRED_VERSION.html?highlight=cmake_minimum_required_version) only say it's being filled in by the `cmake_minimum_required` command.

**Comment by hsorby** [comment]
It was required for an older version of CMake where it wouldn't build due to a bug in that version.
