### ISSUE TITLE
Components sources

### ISSUE THREAD

**Issue by rondiplomatico** [OpenCMISS/manage#11]
Having the ExternalProject manage the sources by "fake" source projects is somewhat unintuitive and a big fuss regarding stamp files. i'd consider re-writing that bit to use own logic using cmake/git command to achieve what little is necessary to
- clone the respective repos
- check for updates
- manage change of branches according to local settings (not sure if that is even handled correctly)

any thoughts?

**Comment by hsorby** [comment]
I think this is reasonable we can take a lot of the ideas out of ExternalProject to implement this.

**Comment by rondiplomatico** [comment]
done in 3443c3b10e49e41b47c899f24b1502121c7989fc
