### ISSUE TITLE
Debug the CMake build system

### ISSUE THREAD

**Issue by rondiplomatico** [OpenCMISS/manage#21]
The question arised to create some sort of global "messagev" macro that can be used to produce some debug output that can be turned on/off.
i'd even go so far as to specify "debug levels" to control verbosity (i.e. error/warn/info/debug/verbose as in many other Log frameworks).
the only thing that needs to well considered is if we want to make the dependencies 
cmake scripts hard-codedly depend on the OpenCMISS-context in the sense of defining the macros somewhere in the manage repo and include that in the single dependencies. i'd rather have the packages being able to build separately, which would mean to include copies of the "Debug.cmake" macros
in every dependency instead of inclusion.

any thoughts?

**Comment by hsorby** [comment]
I would also like independence of the packages.

**Comment by nickerso** [comment]
I also think it would be good to keep the independence of the dependencies. Perhaps putting the common "Debug.cmake" in its own repo and using git submodules to pull it in as needed and keep things synchronised.

**Comment by rondiplomatico** [comment]
Added a "log" function in fcd43261d289ad11e82af1b7311bc5bfad337873 - i think that is well enough for now, and to be honest debugging the dependencies is something not frequently done.
using the submodule-approach seems too much overhead to me..
