### ISSUE TITLE
Component switches

### ISSUE THREAD

**Issue by rondiplomatico** [OpenCMISS/manage#23]
If, for example, one chooses to set "OC_USE_CELLML" to NO and starts building, at latest IRON will fail to build, as the default is IRON_WITH_CELLML=YES.
possible solutions:
1. auto-detect this and have cmake manage those dependent choices
2. document well

comments?

**Comment by nickerso** [comment]
Document well is always a good option :)

Not sure I understand the issue. Is it whether setting the `OC_USE_CELLML` flag should automatically pass through to the corresponding tool-specific flag(s)?

**Comment by rondiplomatico** [comment]
well .. the USE_XX flags are on a global level and determine if a component is built or not.
the XX_WITH_YY flag is more local in the sense that it switches component interaction on/off.
thus, not building cellml but having iron want cellml breaks the build.

alternative idea:
configure all dependencies in a way that they automatically consume any possible package if found and specify a "IRON_DONT_USE_CELLML" like variable instead.
this is also not less robust, as the OC_SYSTEM_XXX flags are still in place and hence the component would automatically only search for own built (=compatible) components.

please comment.

**Comment by nickerso** [comment]
OK, I think I get it now. Your original option 1 seems to be the way to go to me (along with documentation so the confused user can work out why they don't have CellML when they set `OC_USE_CELLML=NO` and `IRON_WITH_CELLML=YES`)

**Comment by chrispbradley** [comment]
Not sure if I fully understand, but can't we either 1) just have one cellml flag i.e., OC_USE_CELLML. If a local flag is really needed just set it to OC_USE_CELLML or 2) Have the build system stop with an error if OC_USE_CELLML is false but IRON_USE_CELL is true?

**Comment by rondiplomatico** [comment]
Okay, so adding extra CMake logic to detect those cases seems a bit overdoing it in the end.
ive added documentation (see OpenCMISSInterComponentConfig.cmake or (staged documentation)[http://staging.opencmiss.org/documentation/cmake/docs/config/index.html], which i deem sufficient at this stage. after all, people messing with the localconfig should know what they're up to
