### ISSUE TITLE
fieldml_api.mod installation

### ISSUE THREAD

**Issue by rondiplomatico** [OpenCMISS/manage#27]
Investigate the issue detected by Shourya:

Hi all,
          I just finished installing OpenCMISS as per the steps in the manual, and I was running the examples. While compiling an example program with 'make install'  I got the following error.
Fatal Error: Can't open module file 'fieldml_api.mod' for reading at (1): No such file or directory.

The 'fieldml_api.mod' was located in the folder 'OpenCMISS/install/release', while the other .mod file were in 'OpenCMISS/install/release/iron' folder. Copying the 'fieldml_api.mod' to the iron folder solved the problem. I'm not sure why this happened, but posting this in case it helps other users / future versions.

Thanks,
Shourya

**Comment by rondiplomatico** [comment]
i've integrated a fieldml example (https://github.com/OpenCMISS-Examples/classicalfield_advectiondiffusion_staticadvectiondiffusion_fieldml) which runs fine with the current development version.
will contact sender again for more details.

**Comment by rondiplomatico** [comment]
alright, found out it was only running because the 'opencmiss' build target i used included zinc which in turn had the correct include path for the fieldml-api.mod file.

the cause is: as fieldml is in fact a private dependency to iron (only the implementation uses fieldml-api modules), its link dependency was not exported as of yet. as one could see the fortran module files as some sort of 'fortran header' (at least for gnu), i think the same CMake paradigm applies than (that for c headers)[https://cmake.org/cmake/help/v3.3/manual/cmake-buildsystem.7.html#transitive-usage-requirements]. hence, i've updated the iron build to expose the dependency on fieldml, having its include path exported to the config and enabling builds against fieldml functionality in iron by just using _find_package(iron)_.

the alternative scenario would be that anyone who wants to use fieldml stuff with iron would also have to issue _find_package(FieldML-API)_.

@chrispbradley could you comment / give that a thought?

**Comment by chrispbradley** [comment]
If I understand correctly option a) is you explicitly export fieldml from iron and then everything works by finding iron and option b) is that people have to explicitly find the fieldml api package? If so then option a) definately seems the way to go to me. Or am I missing the question???

**Comment by nickerso** [comment]
I think that if you want to use the OpenCMISS-Iron API and the FieldML API in your application code then it makes sense that a user needs to find_package(iron) and find_package(fieldml). If you want to use OpenCMISS then a find_package(opencmiss) should be sufficient to find the complete OpenCMISS API.

Its also not clear to me why that example actually even needs FieldML? it seems to be only using the Iron API...

**Comment by chrispbradley** [comment]
Ok, I have missed something. Yes, the example program should not be using the FieldML-API module unless it is directly issuing FieldML calls (which it shouldn't really - it should be using FieldML through iron). It thus shouldn't need the include and it shouldn't be exported as a dependency. Why does it need the include???

**Comment by rondiplomatico** [comment]
well convenience-wise its of course better to just find iron and you're all set.
but its against "common" philosophy of inter-package management - iron itself uses fieldml in its implementation only (no headers), so the fieldml dependency is not really public. consequently, in the classical sense, anyone wanting to use those capabilities would have to take care of their own to install and find a fieldml-api devel package and link against that. so to say, you'd have to _explicitly know_ you need fieldml around. if iron automatically imports fieldml for you, you'll never notice that.

so for now, i've decided to go with the automatic inclusion/export with iron, as fieldml is also a package maintained by us. that also means all that anyone has ever to do is link against iron/zinc and done.

**Comment by chrispbradley** [comment]
There is no question that a find package iron should give you back everything you need to compile an example and link to the library. Thus the find iron should provide a -Lpathtolibs -liron -lfieldml_api -l... etc. However, the example program should not need to have a -Ipathtofieldml_api as there is no need for it to use the fieldml_api package in order for it to compile. If, for some reason, the example program was to issue calls directly to the FieldML API then, yes, it would need the use and -I. However, this would be for that example to manage. Packages management shouldn't be that there are unnecessary -I's -L's or -l's. Shourya doesn't give a particular example but I suspect that a use fieldml_api has been added to the example when it is not needed. The solution is to remove that line rather than add the -I. In saying this I'm assuming that cmake can add a -L and -l without a -I??? This thread also brings up the question of why it worked when zinc was included. Zinc should be in the same position as iron in that it internally uses the fieldml api and so it shouldn't provide a -Ipathtofieldmlinclude either. If this is what it is doing then it should be removed as well.

**Comment by rondiplomatico** [comment]
i've tried removing the USE FIELDML_API line - no joy:

   CALL cmfe_FieldML_OutputWrite( fieldmlInfo, outputFilename, err )
   Error: Symbol 'outputfilename' at (1) has no IMPLICIT type

so it seems we need the module, and that in turn means that this example uses direct fieldml features, right?

**Comment by nickerso** [comment]
might be a side effect from the "C" strings. Maybe try `use iso_c_binding`, which might happen to be also defined in the FieldML API.

**Comment by chrispbradley** [comment]
The cmfe_FieldML_OutputWrite call (and the outputFilename type) should be completely defined by the opencmiss_iron module. Having a look, however, it seems as there are only varying string and  CHARACTER(KIND=C_CHAR,LEN=_). I don't know why somebody has added the KIND=C_CHAR option here as I think it should just be CHARACTER(LEN=_). How is outputFilename defined in the example? Either a normal character string should be added as a module procedure or the definition of outputFilename should be CHARACTER(KIND=C_CHAR,LEN=255) (note: you may need to use iso_c_binding module for the C_CHAR definition).

**Comment by rondiplomatico** [comment]
replacing fieldml_api by iso_c_binding did the job.
i've updated that within the example and will notify Shourya about this.

i consider this specific topic relsolved - the export of fieldml with iron has also been reverted (in the sense that any example explicitly using fieldml and not through iron has to issue a find_package(FieldML-API))

**Comment by chrispbradley** [comment]
Great! What about zinc? Does the cmake need to be fixed for it?

On 18/01/16 13:52, Daniel Wirtz wrote:

> replacing fieldml_api by iso_c_binding did the job.
> i've updated that within the example and will notify Shourya about this.
> 
> i consider this specific topic relsolved - the export of fieldml with
> iron has also been reverted (in the sense that any example explicitly
> using fieldml and not through iron has to issue a find_package(FieldML-API))
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/OpenCMISS/manage/issues/27#issuecomment-172402063.

## 

Chris Bradley
Auckland Bioengineering Institute,
University of Auckland,
Private Bag 92019,
New Zealand.

Tel: +64 9 923 9924
Fax: +64 9 367 7157
