### ISSUE TITLE
Exported OpenCMISS targets 

### ISSUE THREAD

**Issue by rondiplomatico** [OpenCMISS/manage#36]
As @nickerso mentioned in #27 , the exported / linkable targets of opencmiss
still need to be documented and made clear.

following him i suggest:

'opencmiss' target: interface to any component available and built (at OPENCMISS_INSTALL_DIR). 
this target is available in any case.
'iron', 'zinc': can be explicitly searched for via find_package(Iron ..) etc

what about the bindings? e.g. find_package(Iron-C) or have that imported by the Iron package automatically? while there is a useful link target for iron-c (automatically referencing iron), this makes little sense for python, as there is something entirely different in place (setup/pythonpath/virtualenv etc).
i suggest to automatically include the iron_c target to the iron package for now.

**Comment by nickerso** [comment]
> i suggest to automatically include the iron_c target to the iron package for now.

+1

**Comment by chrispbradley** [comment]
Fine by me. We just need to be consistent across the board and across languages.

**Comment by nickerso** [comment]
> We just need to be consistent across the board and across languages.

That gets another +1 from me :)

**Comment by rondiplomatico** [comment]
plot twist: this can create irritating errors. if an example uses iron but "only" imports opencmiss, it could be that whatever installation he provided only contains zinc - then the error message would be "cant find target iron". not having anything in the existing example code that refers to iron is irritating.
my alternative would be to work with (components)[https://cmake.org/cmake/help/v3.3/manual/cmake-packages.7.html?highlight=component#creating-a-package-configuration-file] of the package opencmiss. i've updated the examples to essentially use that, together with an higher-level OpenCMISS.cmake helper file. this file essentially imports opencmiss in the specified version and makes sure all the requested components are there.
this way, any example is written in a way that it is clear which component is needed and there will be no misunderstanding. at the same time, people have the convenience to just link against an "opencmiss" target, which contains anything they requested.

**Comment by rondiplomatico** [comment]
unless there's another language than Fortran or C popping up, we'll simply import all the targets needed to link against the respective bindings (via cmake). this is already done now and presents the easier solution for the not-so-cmake aware/experienced folks out there.
