### ISSUE TITLE
Fortran libraries for Windows/MSMPI case

### ISSUE THREAD

**Issue by rondiplomatico** [OpenCMISS/manage#49]
According to
https://social.microsoft.com/Forums/en-AU/0ffde564-8bc8-4ccd-8991-217278237ed8/problems-linking-fortran-90-code-with-ms-mpi?forum=windowshpcmpi
we have additional fortran libraries to include for the fortran case, but there are two:
- The msmpifec.lib supports compiling where the fortran compiler puts string length at the end of the parameter stack (most common case).
- The msmpifms.lib supports compiling where the Fortran compilers puts the string length right after the string pointer on the parameter stack (mixed).

which one applies to us? i guess this again is fortran compiler dependent (gfortran / intel)? anyone got ideas?

**Comment by chrispbradley** [comment]
From memory I think both intel and gfortran do the end of the parameter stack case. Does this case not work?

**Comment by rondiplomatico** [comment]
Na they both seem fine as far as the build gets - the current devel of manage should pick up the msmpi installation and correct x86/x64 include dirs as well as extra fortran libs.
For my test the compilation of hypre (more exactly examples) failed as there seem to be issues with the MS runtime linked into msmpi.dll and the one in my visual studio. Will investigate.

**Comment by rondiplomatico** [comment]
the original topic of this issue has been resolved with 67f4a25248866614ab43b4b67879e9548ba34011.
