### ISSUE TITLE
MS MPI on Windows

### ISSUE THREAD

**Issue by rondiplomatico** [OpenCMISS/manage#52]
The current manage version can correctly detect MS MPI, but compilation (at least with VS 2013 Update 5) fails with some "symbols redefined" errors at link stage in MSVCRT .. This needs to be investigated further and we need to figure out if there are specific released versions of MS MPI for each Visual Studio or something like that.

**Comment by hsorby** [comment]
Closing this issue as manage now correctly detects and uses MS MPI versions 7 , 8, 8.1 with VS 2015 which is the minimum VS we are trying to support.
