### ISSUE TITLE
Utilities arch path and MPI path

### ISSUE THREAD

**Issue by chrispbradley** [OpenCMISS/manage#65]
The utilities directory under install should have an arch path.  Also, the installed MPI path is different from the rest of the installed dependencies? Is there a reason for this?

**Comment by rondiplomatico** [comment]
utilities: currently there's only CMake in that folder. until we have more possible utilities, why bother? and i for once consider anything under utilities absolutely independent from anything connected to the arch path.

mpi: having the actual mpi installation within its own architecture path makes no sense to me - the path denotes components build _with_ anything appearing in the path. this is also the reason why mpi is contained within the compiler-dependent bit, but not further. the idea is to collect all own mpi builds within `<install_root>/.../<toolchain>/mpi/<mpi-type>`. this way, we have the possible folders "mpi", "mpich / openmpi / younameit" inside the toolchain arch-sub-path. tidy enough for me.

**Comment by hsorby** [comment]
The utilities directory has now been removed, closing this issue.
