### ISSUE TITLE
undefined OC_EP_PREFIX variable

### ISSUE THREAD

**Issue by SpiderMonkey1975** [OpenCMISS/manage#80]
Trying to build OpenCMISS-Iron with the latest manage/devel branch.  The Cmake configuration fails with a message not being able to add the virtualenv_install dependency.  The offending line is line 449 in CMakeScripts/OCConfigureComponents.cmake: 

```
add_dependencies(${OC_EP_PREFIX}IRON virtualenv_install)
```

It appears to occur as part of the Python wrapper setup. However I still hit the error even if I request that Python bindings are not built/installed.

**Comment by PrasadBabarendaGamage** [comment]
Hi all, I also cannot build OpenCMISS due to this error - it fails at the cmake stage. Hoping we can fix this as soon as possible, as without it I can not use OpenCMISS/debug an issue that our masters student is having with solving mechanics problems.

Using: 
`cmake -DEVIL=YES -DOC_PYTHON_BINDINGS_USE_VIRTUALENV=YES -DTOOLCHAIN=GNU -DPYTHON_VERSION:STRING=2 ../`
or 
`cmake -DEVIL=YES ../`
or 
`cmake ../`

produces the following errors:

```
-- Configuring done
CMake Error at CMakeScripts/OCConfigureComponents.cmake:622 (add_dependencies):
  The dependency target "virtualenv_install" of target "OC_ZINC" does not
  exist.
Call Stack (most recent call first):
  CMakeLists.txt:269 (include)

CMake Error at CMakeScripts/OCConfigureComponents.cmake:449 (add_dependencies):
  The dependency target "virtualenv_install" of target "OC_IRON" does not
  exist.
Call Stack (most recent call first):
  CMakeLists.txt:269 (include)
```

**Comment by PrasadBabarendaGamage** [comment]
Its really strange as the devel branch in the prime repo which I am building from hasn't been changed since Oct 2016. I am also building on Ubuntu 16.04 with gcc 5.4.0.
[buildinfo.zip](https://github.com/OpenCMISS/manage/files/887442/buildinfo.zip)

**Comment by SpiderMonkey1975** [comment]
Hi Prasad,

Spoke with Hugh on Friday. He has switched the development branch from 'devel' to 'develop'. You should specify that branch in OpenCMISS eloper.cmake and try the build again.

Maybe this branch switch should be documented somewhere?

On Apr 1, 2017 8:06 PM, Prasad <notifications@github.com> wrote:

Its really strange as the devel branch in the prime repo which I am building from hasn't been changed since Oct 2016. I am also building on Ubuntu 16.04 with gcc 5.4.0.
buildinfo.zip<https://github.com/OpenCMISS/manage/files/887442/buildinfo.zip>

**Comment by PrasadBabarendaGamage** [comment]
Thanks Mark,

I cloned a new manage repo and switched the branch to develop, but now it is saying OCArchitecturePathFunctions.cmake' does not exists in the install dir (located outside the manage folder). Please see full error at the bottom of this message. Just wondering if you also had this error?

It also seems that there is no OpenCMISSDeveloper.cmake anymore, only a OpenCMISSInstallationConfig.cmake. I changed the file in the mange folder. However the error below occurs regardless of whether I change OpenCMISSInstallationConfig.cmake or not (I think the error happens very early on during the cmake run). Here is my edited copy of the OpenCMISSInstallationConfig.cmake file (I changed the extension to .txt so I could upload it here)  [OpenCMISSInstallationConfig.txt](https://github.com/OpenCMISS/manage/files/887921/OpenCMISSInstallationConfig.txt)

I'll make a github issue regarding documenting the manage branch change and create another issue regarding the build problem.

Thanks,

Prasad


```
CMake Error at CMakeLists.txt:63 (message):
  '/home/psam012/opt/OpenCMISS/install/share/cmake/Modules/OpenCMISS/OCArchitecturePathFunctions.cmake'
  does not exists.  The OpenCMISS CMake modules may not be
  installed/available.

```

**Comment by PrasadBabarendaGamage** [comment]
Here is the new github issue regarding the OCArchitecturePathFunctions.cmake build error https://github.com/OpenCMISS/manage/issues/81

Here is the new github issue regarding documenting the manage branch change https://github.com/OpenCMISS/manage/issues/82

**Comment by hsorby** [comment]
This issue has now been resolved.
