### ISSUE TITLE
Building OpenCMISS fails using the develop branch of manage

### ISSUE THREAD

**Issue by PrasadBabarendaGamage** [OpenCMISS/manage#81]
The following error occurs when trying to build OpenCMISS using the develop branch of manage:
```
CMake Error at CMakeLists.txt:63 (message):
  '/home/psam012/opt/OpenCMISS/install/share/cmake/Modules/OpenCMISS/OCArchitecturePathFunctions.cmake'
  does not exists.  The OpenCMISS CMake modules may not be
  installed/available.
```

Commands used:
```
git clone https://github.com/OpenCMISS/manage
cd manage/
git checkout develop
mkdir build-release
cd build-release/
```
`cmake -DEVIL=YES ../ ` or `cmake ../`

**Comment by nickerso** [comment]
Do you have the OpenCMISS/cmake_modules "installed"? I think that is something the setup will do for you, but you might need to do that yourself if using manage directly. Maybe.

**Comment by PrasadBabarendaGamage** [comment]
I don't think I have it installed - not too sure where to install/clone it too (it seems it is supposed to go into the install folder?). I thought that setup and manage were different (there is no  documentation linking the two e.g. I was following: http://staging.opencmiss.org/documentation/building/cmake/manage/docs/build/index.html#building-on-linux). Also thought that developers should only be using manage as setup doesn't allow debug builds?

My overall aim is to create a debug and release build that both use the same underlying fork of my iron repo.

Thinking it might be best to wait for Hugh to clarify how it works as some of the changes to the develop branch of manage were committed within the last few days.

**Comment by SpiderMonkey1975** [comment]
I am encountering a build error using a branch from 'develop' as well.  Don't know anything about the setup project as there is no documentation.  When will this be fixed?

Performing configure step for 'OC_IRON'
Not searching for unused variables given on the command line.
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- The Fortran compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/mpicc
-- Check for working C compiler: /usr/bin/mpicc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/mpicxx
-- Check for working CXX compiler: /usr/bin/mpicxx -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working Fortran compiler: /usr/bin/mpif90
-- Check for working Fortran compiler: /usr/bin/mpif90  -- works
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Checking whether /usr/bin/mpif90 supports Fortran 90
-- Checking whether /usr/bin/mpif90 supports Fortran 90 -- yes
CMake Error at CMakeLists.txt:71 (include):
  include could not find load file:

    OCMiscFunctions


CMake Error at CMakeLists.txt:72 (include):
  include could not find load file:

    OCMultiConfigEnvironment


-- Found MPI_C: /usr/lib/x86_64-linux-gnu/libmpich.so
-- Found MPI_CXX: /usr/lib/x86_64-linux-gnu/libmpichcxx.so;/usr/lib/x86_64-linux-gnu/libmpich.so
-- Performing Test MPI_Fortran_MODULE_COMPATIBLE
-- Performing Test MPI_Fortran_MODULE_COMPATIBLE - Success
-- Found MPI_Fortran: /usr/lib/x86_64-linux-gnu/libmpichfort.so;/usr/lib/x86_64-linux-gnu/libmpich.so
-- FindLibXml2 wrapper: System search enabled
-- FindLibXml2 wrapper: Trying to find version 2.7.6 on system in MODULE mode
-- FindLibXml2 wrapper: Trying to find version 2.7.6 on system in CONFIG mode
-- FindLibXml2 wrapper: No system package found/available.
-- FindZLIB wrapper: Found version 1.2.3 at /home/mche807/OpenCMISS/install/x86_64_linux/gnu-5.4-F5.4/no_mpi/debug/cmake in CONFIG mode
-- FindLibXml2 wrapper: Found at /home/mche807/OpenCMISS/install/x86_64_linux/gnu-5.4-F5.4/no_mpi/debug/cmake in CONFIG mode
-- Building with CELLML (/home/mche807/OpenCMISS/install/x86_64_linux/gnu-5.4-F5.4/no_mpi/debug/cmake)
-- Building with FIELDML (/home/mche807/OpenCMISS/install/x86_64_linux/gnu-5.4-F5.4/no_mpi/debug/cmake)
-- Looking for PETSC..
-- FindBLAS wrapper: System search enabled
-- FindBLAS wrapper: Trying to find version 3.5.0 on system in MODULE mode
-- Looking for Fortran dgemm
-- Looking for Fortran dgemm - found
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- FindBLAS wrapper: Found: /usr/lib/libf77blas.so;/usr/lib/libatlas.so
-- FindBZip2 wrapper: Found version 1.0.6 at /home/mche807/OpenCMISS/install/x86_64_linux/gnu-5.4-F5.4/no_mpi/debug/cmake in CONFIG mode
-- FindPTSCOTCH wrapper: Found version 6.0.3 at /home/mche807/OpenCMISS/install/x86_64_linux/gnu-5.4-F5.4/mpich_release/debug/cmake in CONFIG mode
-- FindPASTIX wrapper: Found version 5.2.2.16 at /home/mche807/OpenCMISS/install/x86_64_linux/gnu-5.4-F5.4/mpich_release/debug/cmake in CONFIG mode
-- FindPARMETIS wrapper: Found version  at /home/mche807/OpenCMISS/install/x86_64_linux/gnu-5.4-F5.4/mpich_release/debug/cmake in CONFIG mode
-- FindMUMPS wrapper: Found version 5.0.0 at /home/mche807/OpenCMISS/install/x86_64_linux/gnu-5.4-F5.4/mpich_release/debug/cmake in CONFIG mode
-- FindLAPACK wrapper: System search enabled
-- FindLAPACK wrapper: Trying to find version 3.5.0 on system in MODULE mode
-- A library with BLAS API found.
-- Looking for Fortran cheev
-- Looking for Fortran cheev - found
-- FindLAPACK wrapper: Found: /usr/lib/liblapack.so;/usr/lib/libf77blas.so;/usr/lib/libatlas.so
-- FindSUITESPARSE wrapper: Found version 4.4.0 at /home/mche807/OpenCMISS/install/x86_64_linux/gnu-5.4-F5.4/mpich_release/debug/cmake in CONFIG mode
-- FindSCALAPACK wrapper: Found version 2.8 at /home/mche807/OpenCMISS/install/x86_64_linux/gnu-5.4-F5.4/mpich_release/debug/cmake in CONFIG mode
-- FindSUPERLU wrapper: Found version 4.3 at /home/mche807/OpenCMISS/install/x86_64_linux/gnu-5.4-F5.4/no_mpi/debug/cmake in CONFIG mode
-- FindSUNDIALS wrapper: Found version 2.5 at /home/mche807/OpenCMISS/install/x86_64_linux/gnu-5.4-F5.4/mpich_release/debug/cmake in CONFIG mode
-- FindHYPRE wrapper: Found version 2.10.0 at /home/mche807/OpenCMISS/install/x86_64_linux/gnu-5.4-F5.4/mpich_release/debug/cmake in CONFIG mode
-- FindSUPERLU_DIST wrapper: Found version 4.1 at /home/mche807/OpenCMISS/install/x86_64_linux/gnu-5.4-F5.4/mpich_release/debug/cmake in CONFIG mode
-- FindPETSC wrapper: Found version 3.6.1 at /home/mche807/OpenCMISS/install/x86_64_linux/gnu-5.4-F5.4/mpich_release/debug/cmake in CONFIG mode
-- Looking for PETSC.. found at /home/mche807/OpenCMISS/install/x86_64_linux/gnu-5.4-F5.4/mpich_release/debug/cmake
-- Looking for SUNDIALS..
-- FindSUNDIALS wrapper: Found version 2.5 at /home/mche807/OpenCMISS/install/x86_64_linux/gnu-5.4-F5.4/mpich_release/debug/cmake in CONFIG mode
-- Looking for SUNDIALS.. found at /home/mche807/OpenCMISS/install/x86_64_linux/gnu-5.4-F5.4/mpich_release/debug/cmake
-- Looking for HYPRE..
-- FindHYPRE wrapper: Found version 2.10.0 at /home/mche807/OpenCMISS/install/x86_64_linux/gnu-5.4-F5.4/mpich_release/debug/cmake in CONFIG mode
-- Looking for HYPRE.. found at /home/mche807/OpenCMISS/install/x86_64_linux/gnu-5.4-F5.4/mpich_release/debug/cmake
-- Looking for MUMPS..
-- FindMUMPS wrapper: Found version 5.0.0 at /home/mche807/OpenCMISS/install/x86_64_linux/gnu-5.4-F5.4/mpich_release/debug/cmake in CONFIG mode
-- Looking for MUMPS.. found at /home/mche807/OpenCMISS/install/x86_64_linux/gnu-5.4-F5.4/mpich_release/debug/cmake
-- Looking for SCALAPACK..
-- FindSCALAPACK wrapper: Found version 2.8 at /home/mche807/OpenCMISS/install/x86_64_linux/gnu-5.4-F5.4/mpich_release/debug/cmake in CONFIG mode
-- Looking for SCALAPACK.. found at /home/mche807/OpenCMISS/install/x86_64_linux/gnu-5.4-F5.4/mpich_release/debug/cmake
-- Looking for SA_NODEFER
-- Looking for SA_NODEFER - not found
-- Looking for sigaction
-- Looking for sigaction - found
-- Creating C bindings
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY - Success
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY - Success
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Success
-- Creating Python bindings
CMake Error at bindings/CMakeLists.txt:74 (three_part_version_to_vars):
  Unknown CMake command "three_part_version_to_vars".


-- Configuring incomplete, errors occurred!
See also "/home/mche807/OpenCMISS/build/x86_64_linux/gnu-5.4-F5.4/mpich_release/iron/debug/CMakeFiles/CMakeOutput.log".
See also "/home/mche807/OpenCMISS/build/x86_64_linux/gnu-5.4-F5.4/mpich_release/iron/debug/CMakeFiles/CMakeError.log".
CMakeFiles/OC_IRON.dir/build.make:122: recipe for target '/home/mche807/OpenCMISS/build/x86_64_linux/gnu-5.4-F5.4/mpich_release/iron/debug/ep_stamps/OC_IRON-configure' failed
make[2]: *** [/home/mche807/OpenCMISS/build/x86_64_linux/gnu-5.4-F5.4/mpich_release/iron/debug/ep_stamps/OC_IRON-configure] Error 1
CMakeFiles/Makefile2:4956: recipe for target 'CMakeFiles/OC_IRON.dir/all' failed
make[1]: *** [CMakeFiles/OC_IRON.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by dladd** [comment]
Any movement on this in the last few weeks? I've also run into both of these issues trying to build with the latest manage:develop (unable to locate OCArchitecturePathFunctions.cmake and OCMiscFunctions/OCMultiConfigEnvironment)

**Comment by PrasadBabarendaGamage** [comment]
Hi David, just wondering if you are building OpenCMISS through setup? I just tried building again last night and it seems to be building. Hugh is still working on the build documentation. However, for now, I've added a doc with some build instructions based on conversations with Hugh and Chris to the OpenCMISS shared google drive https://docs.google.com/document/d/13t3dfpgfQGLhc2JrVhvqj32wGDk1N4Hc6vC7d09v1GE/edit#
We also have a OpenCMISS developers slack channel. Please feel free to join https://opencmiss-developers.slack.com/signup Please send me an email if you can't get access. 
Cheers Prasad

**Comment by PrasadBabarendaGamage** [comment]
Forgot to mention @dladd

**Comment by dladd** [comment]
Thanks Prasad! I've got manage built now with branch v1.2. But I will have another crack with setup and develop per your instructions if I get some time a bit later. Thanks for letting me know about the slack channel too.

**Comment by hsorby** [comment]
OpenCMISS libraries are now building with develop branch across all tested operating systems.
