### ISSUE TITLE
Manage wants to check OpenMPI sources are there and build OpenMPI when MPICH is requested.

### ISSUE THREAD

**Issue by chrispbradley** [OpenCMISS/manage#83]
[bn356540]>cd build/manage/release/
[bn356540]>cmake -DOPENCMISS_MPI=mpich -DOPENCMISS_TOOLCHAIN=gnu -DOPENCMISS_BUILD_TYPE=debug .
-- Applying OpenCMISS installation configuration at /data/OpenCMISS/build/manage/release/OpenCMISSInstallationConfig.cmake...
-- Setting user specified MPI to TRUE
-- Looking for 'mpich' MPI on local system.
-- Looking for MPI: mpich specified by user.
-- MPI is set to: mpich, and it is available
-- CONFIGURATION_SETTINGS: -DOPENCMISS_BUILD_TYPE=debug -DOPENCMISS_TOOLCHAIN=gnu -DOPENCMISS_MPI=mpich -DOPENCMISS_BUILD_OWN_MPI=NO -DOPENCMISS_INSTRUMENTATION=none -DOPENCMISS_OWN_MPI_INSTALL_BASE=/data/OpenCMISS/install -DOPENCMISS_INSTALLATION_CACHE_FILE=/data/OpenCMISS/build/manage/release/OpenCMISSCache.cmake -DOPENCMISS_CMAKE_MODULE_PATH=/data/OpenCMISS/install/share/cmake -DARCH_MPI_PATH=/x86_64_linux/gnu-C6.3-gnu-F6.3/mpich_release -DARCH_NO_MPI_PATH=/x86_64_linux/gnu-C6.3-gnu-F6.3/no_mpi -DOpenCMISSLibs_VERSION=1.3.0
-- @
-- @@@@@@@@@@@@@@@@@@@@@ SUMMARY @@@@@@@@@@@@@@@@@@@@@@@
-- @
-- @ OPENCMISS_TOOLCHAIN: gnu
-- @ OPENCMISS_MPI: mpich
-- @ ACTIVE_ARCHITECTURE_MPI_PATH: /x86_64_linux/gnu-C6.3-gnu-F6.3/mpich_release
-- @
-- @ CONFIG PATH: /data/OpenCMISS/build/manage/release/configs/x86_64_linux/gnu-C6.3-gnu-F6.3/mpich_release/debug
-- @ CONFIGURATION SETTINGS: -DOPENCMISS_BUILD_TYPE=debug -DOPENCMISS_TOOLCHAIN=gnu -DOPENCMISS_MPI=mpich -DOPENCMISS_BUILD_OWN_MPI=NO -DOPENCMISS_INSTRUMENTATION=none -DOPENCMISS_OWN_MPI_INSTALL_BASE=/data/OpenCMISS/install -DOPENCMISS_INSTALLATION_CACHE_FILE=/data/OpenCMISS/build/manage/release/OpenCMISSCache.cmake -DOPENCMISS_CMAKE_MODULE_PATH=/data/OpenCMISS/install/share/cmake -DARCH_MPI_PATH=/x86_64_linux/gnu-C6.3-gnu-F6.3/mpich_release -DARCH_NO_MPI_PATH=/x86_64_linux/gnu-C6.3-gnu-F6.3/no_mpi -DOpenCMISSLibs_VERSION=1.3.0
-- @
-- @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
-- @
-- @
-- @@@@@@@@@@@@@@@@@@@ NEXT STEPS @@@@@@@@@@@@@@@@@@@@@@
-- @
-- @ - Change /data/OpenCMISS/build/manage/release/OpenCMISSInstallationConfig.cmake according to your needs
-- @
-- @ Having trouble? Follow the galaxy hitchhiker's advice:
-- @ DONT PANIC ... and:
-- @ - Refer to http://staging.opencmiss.org/documentation/cmake/docs/config/index.html for customization instructions
-- @
-- @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
-- @
-- Configuring done
-- Generating done
-- Build files have been written to: /data/OpenCMISS/build/manage/release
[bn356540]>make create_config
Scanning dependencies of target openmpi_sources
[  4%] Checking OPENMPI sources are present
Scanning dependencies of target openmpi_download
Cloning OPENMPI sources
SourceManagement/CMakeFiles/openmpi_download.dir/build.make:57: recipe for target 'SourceManagement/CMakeFiles/openmpi_download' failed
CMakeFiles/Makefile2:3011: recipe for target 'SourceManagement/CMakeFiles/openmpi_download.dir/all' failed
CMakeFiles/Makefile2:3018: recipe for target 'SourceManagement/CMakeFiles/openmpi_download.dir/rule' failed
Makefile:1296: recipe for target 'SourceManagement/CMakeFiles/openmpi_download.dir/rule' failed
CMake Error at /data/OpenCMISS/src/manage/SourceManagement/Scripts/OCSourceManager.cmake:17 (message):
  Error downloading openmpi: fatal: destination path '.' already exists and
  is not an empty directory.

  gmake[7]: *** [SourceManagement/CMakeFiles/openmpi_download] Error 128

  gmake[6]: *** [SourceManagement/CMakeFiles/openmpi_download.dir/all] Error
  2

  gmake[5]: *** [SourceManagement/CMakeFiles/openmpi_download.dir/rule] Error
  2

  gmake[4]: *** [SourceManagement/CMakeFiles/openmpi_download.dir/rule] Error
  2

SourceManagement/CMakeFiles/openmpi_sources.dir/build.make:57: recipe for target 'SourceManagement/CMakeFiles/openmpi_sources' failed
make[3]: *** [SourceManagement/CMakeFiles/openmpi_sources] Error 1
CMakeFiles/Makefile2:6147: recipe for target 'SourceManagement/CMakeFiles/openmpi_sources.dir/all' failed
make[2]: *** [SourceManagement/CMakeFiles/openmpi_sources.dir/all] Error 2
CMakeFiles/Makefile2:208: recipe for target 'CMakeFiles/create_config.dir/rule' failed
make[1]: *** [CMakeFiles/create_config.dir/rule] Error 2
Makefile:181: recipe for target 'create_config' failed
make: *** [create_config] Error 2

**Comment by hsorby** [comment]
There are several things going on here, the first being the major one:

1. A build has already been attempted and failed leaving behind some files which caused problems for the current build.
2. The second (and very minor) -DOPENCMISS_BUILD_TYPE=debug should be -DOPENCMISS_BUILD_TYPE=Debug with a capital D for debug.
3. It is not actually trying to build the OpenMPI libraries here it is just making sure that it has the source files should it wish to do so later (which it shouldn't).

**Comment by hsorby** [comment]
Closing this issue.  The source download is not smart and so just retrieves everything it may need regardless of whether it is required or not.  This though is a separate issue to what happened here.
